import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })

// styles
import './globals.css'
import '../../public/css/bootstrap.min.css'
import '../../public/css/font-awesome.min.css'
import '../../public/css/xsIcon.css'
import '../../public/css/isotope.css'
import '../../public/css/magnific-popup.css'
import '../../public/css/owl.carousel.min.css'
import '../../public/css/owl.theme.default.min.css'
import '../../public/css/animate.css'
import '../../public/css/plugins.css'
import '../../public/css/style.css'
import '../../public/css/responsive.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
